import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { cn } from "@/lib/utils";
export function KpiCard({ label, value, unit, hint, icon, className, progress, badge, variant = "small", }) {
    return (_jsxs("div", { className: cn("print-card bg-[#131C2E] border border-[#1E293B] rounded-[10px] shadow-lg backdrop-blur-sm p-4 flex flex-col justify-between items-center text-center min-h-[140px] h-full transition-all hover:shadow-black/20 relative group overflow-hidden", className), children: [badge && (_jsx("div", { className: cn("absolute top-3 right-3 px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-tighter opacity-70 group-hover:opacity-100 transition-opacity", badge.variant === "success" && "bg-emerald-500/20 text-emerald-400 border border-emerald-500/30", badge.variant === "warning" && "bg-amber-500/20 text-amber-400 border border-amber-500/30", badge.variant === "danger" && "bg-rose-500/20 text-rose-400 border border-rose-500/30", badge.variant === "default" && "bg-slate-500/20 text-slate-400 border border-slate-500/30"), children: badge.text })), _jsxs("header", { className: "flex items-center justify-center w-full", children: [
                    _jsx("span", { className: "text-[10px] font-bold uppercase tracking-[0.15em] text-[#94A3B8]", children: label }), icon && !badge ? _jsx("span", { className: "ml-2 text-amber-500", children: icon }) : null] }), _jsxs("div", { className: "flex flex-col flex-1 justify-center py-2 w-full overflow-hidden", children: [
                    _jsxs("div", { className: "flex flex-col items-center", children: [
                            _jsx("p", { className: cn("font-bold tracking-tight text-slate-100 text-ellipsis overflow-hidden whitespace-nowrap w-full", variant === "large" ? "text-3xl md:text-4xl" : "text-3xl"), children: value }), unit ? (_jsx("span", { className: "text-xs uppercase tracking-wider text-slate-400 font-medium block mt-1", children: unit })) : null] }), progress && (_jsxs("div", { className: "mt-3 w-full", children: [
                            _jsx("div", { className: "h-1.5 w-full bg-slate-800/50 rounded-full overflow-hidden", children: _jsx("div", { className: "h-full rounded-full transition-all duration-1000", style: {
                                        width: `${progress.value}%`,
                                        backgroundColor: progress.color
                                    } }) }), _jsxs("p", { className: "mt-1.5 text-[10px] font-medium text-slate-500", children: [progress.value.toFixed(0), "% do total"] })
                        ] }))] }), hint ? (_jsx("p", { className: "text-sm font-medium text-[#F59E0B]", children: hint })) : null] }));
}
